### ISSUE TITLE
edit label after file upload

### ISSUE THREAD

**Issue by ted19b** [flexudy-pipe/labely#2]
once the csv file is uploaded, it is unfortunately no longer possible to modify the labels we had defined. 

In case of keystroke errors we have to start the process from the beginning again.

it would be nice to have the possibility to modify the labels, even once we have started to label the data.

**Comment by collins-k** [comment]
Thanks for noticing this. We will try to solve this ASAP. We will be happy if you fork the project fix the issue and make a PR

**Comment by collins-k** [comment]
With the new version of labely it is actually possible to delete a label and add a new one
