### ISSUE TITLE
error when selecting label

### ISSUE THREAD

**Issue by rjtch** [flexudy-pipe/labely#4]
When i enter a label many times i get the same label displayed many times. 

<img width="1026" alt="labeling" src="https://user-images.githubusercontent.com/23282107/91430676-8b9bc480-e85f-11ea-9b78-e0b11f362128.png">

**Comment by collins-k** [comment]
Thanks for noticing this. We will try to solve this ASAP. We will be happy if you fork the project fix the issue and make a PR

**Comment by rjtch** [comment]
yes i can fix it no problem

**Comment by collins-k** [comment]
This issue was solve with the new version of labely
